# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
permalink: pretty
title: William Perkola
description: >
  Master's student in computer science at the Royal Institute of Technology in Stockholm, Sweden. I have a passion for learning new things, building websites and growing tomatoes.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://perko.la" # the base hostname & protocol for your site
github: perkola
linkedin: perkola
twitter: WilliamPerkola
collections:
  projects:
    output: true
    layout: project

# Build settings
markdown: kramdown
